---
version: 2
updates:
  - package-ecosystem: terraform
    directory: terraform
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: .github/workflows
    schedule:
      interval: daily
