---
apiVersion: v2
name: video
description: A Helm chart for deploying the video container
type: application
version: 0.1.1
appVersion: "1.0.0"
icon: "https://upload.wikimedia.org/wikipedia/commons/3/3c/Fortinet_logo.png"
