---
# Default values for video.

image:
  repository: your-docker-repo/video
  tag: "latest"
  pullPolicy: Always

replicaCount: 1

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: video.local
      paths:
        - path: /video/
          pathType: ImplementationSpecific
  tls: []

resources: {}

