---
name: Version Increment, Build, and Push Video

on:
  repository_dispatch:
    types: [features]
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'main.py'
      - 'assets/*'
      - '*.mlt'
      - 'VERSION'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  version-and-build:
    timeout-minutes: 1440
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Verify VERSION file exists or create one
        id: check_version
        run: |
          if [ ! -f VERSION ]; then
            echo "VERSION file not found! Creating a new one with the initial value 0.0.1."
            echo "0.0.1" > VERSION
          fi

      - name: Validate VERSION format
        id: validate_version
        run: |
          VERSION_CONTENT=$(cat VERSION)
          if [[ ! "$VERSION_CONTENT" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid version format: $VERSION_CONTENT. It should follow x.x.x format."
            exit 1
          fi
          echo "current_version=$VERSION_CONTENT" >> $GITHUB_ENV

      - name: Increment Version if Pushed to Main
        if: github.ref == 'refs/heads/main'
        id: increment_version
        run: |
          version=$(cat VERSION)
          IFS='.' read -r major minor patch <<< "$version"
          new_patch=$((patch + 1))
          new_version="$major.$minor.$new_patch"
          echo $new_version > VERSION
          echo "New version: $new_version"
          echo "new_version=$new_version" >> $GITHUB_ENV

      - name: Commit and Push New Version
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b version-increment
          git add VERSION
          git commit -m "Increment version to ${{ env.new_version }}"
          git push origin version-increment

      - name: Create Pull Request for New Version
        if: github.ref == 'refs/heads/main'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: version-increment
          title: Increment version to ${{ env.new_version }}
          body: This pull request increments the version in the VERSION file to ${{ env.new_version }}.

      - name: Read version from VERSION file
        id: read_version
        run: |
          VERSION=$(cat VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set up QEMU for multi-architecture builds
        uses: docker/setup-qemu-action@v2
        with:
          platforms: "linux/amd64"

      - name: Setup Docker buildx for multi-architecture builds
        uses: docker/setup-buildx-action@v2
        with:
          use: true
        env:
          BUILDX_NO_DEFAULT_ATTESTATIONS: 1

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: "ghcr.io"
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/video:latest
            ghcr.io/${{ github.repository_owner }}/video:${{ env.VERSION }}
