name: Compile and Publish Helm Chart as Gist

on:
  push:
    branches:
      - main  # Or any other branch you want to trigger the action
    paths:
      - 'Chart.yaml'
      - 'values.yaml'
      - 'templates/**'  # This triggers the action if any file inside the 'templates' directory changes
      - 'VERSION'  # Include the VERSION file in the paths list

  workflow_dispatch:  # This adds the manual trigger option

jobs:
  publish_gist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@3b24654d6b515a88a9fae601fcb00c2da2f1f8a7  # SHA for actions/checkout@v3

    - name: Set up Helm
      uses: azure/setup-helm@68037e3f7beef75a71d283ab7d7f9e10c6ae13d7  # SHA for azure/setup-helm@v3

    - name: Package Helm chart
      run: helm package .

    - name: Install GitHub CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y gh

    - name: Create Gist with GitHub CLI
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Create the Gist using GitHub CLI and upload the Helm chart
        GIST_URL=$(gh gist create *.tgz --public --desc "Helm chart for video application")
        echo "Gist URL: $GIST_URL"
