name: Compile and Publish Helm Chart as Gist

on:
  push:
    branches:
      - main  # Or any other branch you want to trigger the action
    paths:
      - 'Chart.yaml'
      - 'values.yaml'
      - 'templates/**'
      - 'VERSION'

  workflow_dispatch:  # Manual trigger option

jobs:
  publish_gist:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938  # Correct SHA for actions/checkout

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Install Helm
      uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@a917fd15b20e8b64b94d9158ad54cd6345335584  # Use the specific SHA for chart-releaser-action
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"  # Set the CR_TOKEN to authenticate with GitHub
      with:
        charts_dir: '.'  # Helm chart located in the root of the repository

