name: Compile and Publish Helm Chart as Gist

on:
  push:
    branches:
      - main  # Or any other branch you want to trigger the action
    paths:
      - 'Chart.yaml'
      - 'values.yaml'
      - 'templates/**'
      - 'VERSION'

  workflow_dispatch:  # Manual trigger option

jobs:
  publish_gist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938  # Correct SHA for actions/checkout

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@a917fd15b20e8b64b94d9158ad54cd6345335584  # Use the specific SHA for chart-releaser-action
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"  # Set the CR_TOKEN to authenticate with GitHub
      with:
        charts_dir: '.'  # Helm chart located in the root of the repository

    - name: List directory contents for debugging
      run: ls -lah

    - name: Install GitHub CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y gh

    - name: Create Gist with GitHub CLI
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Check if the .tgz file exists and create the Gist
        if ls *.tgz 1> /dev/null 2>&1; then
          GIST_URL=$(gh gist create *.tgz --public --desc "Helm chart for video application")
          echo "Gist URL: $GIST_URL"
        else
          echo "No .tgz file found, aborting."
          exit 1
        fi
