name: Compile and Publish Helm Chart as Gist

on:
  push:
    branches:
      - main  # Or any other branch you want to trigger the action
    paths:
      - 'Chart.yaml'
      - 'values.yaml'
      - 'templates/**'  # This triggers the action if any file inside the 'templates' directory changes

jobs:
  publish_gist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.12.0

    - name: Package Helm chart
      run: helm package ./video-app

    - name: Install GitHub CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y gh

    - name: Create Gist with GitHub CLI
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Create the Gist using GitHub CLI and upload the Helm chart
        GIST_URL=$(gh gist create video-app-*.tgz --public --desc "Helm chart for video application")
        echo "Gist URL: $GIST_URL"
