name: Compile and Publish Helm Chart as Gist

on:
  push:
    branches:
      - main  # Or any other branch you want to trigger the action
    paths:
      - 'Chart.yaml'
      - 'values.yaml'
      - 'templates/**'  # This triggers the action if any file inside the 'templates' directory changes
      - 'VERSION'  # Include the VERSION file in the paths list

  workflow_dispatch:  # This adds the manual trigger option

jobs:
  publish_gist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938  # SHA for actions/checkout@v3

    - name: Package Helm chart with chart-releaser
      uses: helm/chart-releaser-action@a917fd15b20e8b64b94d9158ad54cd6345335584  # Use the latest release version
      with:
        charts_dir: '.'  # Helm chart located in the root of the repository

    - name: Install GitHub CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y gh

    - name: Create Gist with GitHub CLI
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Create the Gist using GitHub CLI and upload the Helm chart
        GIST_URL=$(gh gist create *.tgz --public --desc "Helm chart for video application")
        echo "Gist URL: $GIST_URL"
