name: Compile and Publish Helm Chart as Gist

on:
  push:
    branches:
      - main  # Or any other branch you want to trigger the action
    paths:
      - 'Chart.yaml'
      - 'values.yaml'
      - 'templates/**'
      - 'VERSION'

  workflow_dispatch:  # Manual trigger option

jobs:
  publish_gist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938  # Correct SHA for actions/checkout

    - name: Set up Helm
      uses: azure/setup-helm@68037e3f7beef75a71d283ab7d7f9e10c6ae13d7  # Correct SHA for azure/setup-helm

    - name: Package Helm chart
      run: helm package .

    - name: List directory contents for debugging
      run: ls -lah

    - name: Install GitHub CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y gh

    - name: Create Gist with GitHub CLI
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Check if the .tgz file exists and create the Gist
        if ls *.tgz 1> /dev/null 2>&1; then
          GIST_URL=$(gh gist create *.tgz --public --desc "Helm chart for video application")
          echo "Gist URL: $GIST_URL"
        else
          echo "No .tgz file found, aborting."
          exit 1
        fi
