name: Increment Version

on:
  push:
    branches:
      - main

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Verify VERSION file exists or create one
        id: check_version
        run: |
          if [ ! -f VERSION ]; then
            echo "VERSION file not found! Creating a new one with the initial value 0.0.1."
            echo "0.0.1" > VERSION
          fi

      - name: Validate VERSION format
        id: validate_version
        run: |
          VERSION_CONTENT=$(cat VERSION)
          if [[ ! "$VERSION_CONTENT" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid version format: $VERSION_CONTENT. It should follow x.x.x format."
            exit 1
          fi
          echo "::set-output name=current_version::$VERSION_CONTENT"

      - name: Increment Version
        id: increment_version
        run: |
          version=$(cat VERSION)
          IFS='.' read -r major minor patch <<< "$version"
          new_patch=$((patch + 1))
          new_version="$major.$minor.$new_patch"
          echo $new_version > VERSION
          echo "New version: $new_version"
          echo "::set-output name=new_version::$new_version"

      - name: Commit and Push New Version
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b version-increment
          git add VERSION
          git commit -m "Increment version to ${{ steps.increment_version.outputs.new_version }}"
          git push origin version-increment

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: version-increment
          title: Increment version to ${{ steps.increment_version.outputs.new_version }}
          body: This pull request increments the version in the VERSION file to ${{ steps.increment_version.outputs.new_version }}.

